# Spring Configuration
spring:
  application:
    name: item
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki_item
    username: mujiki_item
    password: nothing

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:logs/db.changelog-master.xml
    enabled: true

# API Configuration
api:
  endpoint:
    base-url: /api

# API Configuration for all services
user:
  url:
    service: http://localhost:8081/api/user

restaurant:
  url:
    service: http://localhost:8082/api/restaurant

address:
  url:
    service: http://localhost:8086/api/address

# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 8085



